name: CI

on:
  push:
    branches:
      - main

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm i

      - name: Run tests
        run: pnpm test:run

      - name: Run TypeScript type checking
        run: pnpm type-check

      - name: Run ESLint and fix
        run: pnpm lint:fix

      - name: Format with Prettier
        run: pnpm format

      - name: Check for remaining ESLint errors
        run: pnpm lint

      - name: Check for remaining formatting issues
        run: pnpm format:check
